config/routes.rb
NewDay0::Application.routes.draw do
  root :to => 'home#index'
  devise_for :users, :controllers => { :ajax_registrations => "devise/ajax_registrations", :ajax_sessions => "devise/ajax_sessions"  }
  devise_scope :user do
    get 'ajax_new' => 'devise/ajax_registrations#new', as: 'ajax_registration_new'
    get 'json_new' => 'devise/ajax_registrations#json_new', as: 'json_registration_new'
    post 'ajax_create' => 'devise/ajax_registrations#create', as: 'ajax_registration_create'
    get 'ajax_session_new' => 'devise/ajax_sessions#new', as: 'ajax_session_new'
    post 'ajax_session_create' => 'devise/ajax_sessions#create', as: 'ajax_session_create'
    match '/auth/:provider/callback', to: 'omniauth_callbacks#create', as: 'auth_provider_user', via: [:get, :post]
    match '/auth/failure', to: 'omniauth_callbacks#failure', via: [:get, :post]
  end

  get 'authed_request' => 'home#authed_request', as: 'authed_request'
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!, only: [:authed_request]

  def index
  end

  def authed_request
    render json: {success: true, data: "it's a boy!"}
  end
end

app/views/home/_facebook_login.html.erb
<div id="fb-root"></div>

<div id="connect" class="connect-facebook">
  <a href= "#" class="btn facebook login"> Connect with Facebook</a>
</div>

<script>

  // Additional JS functions here
  window.fbAsyncInit = function() {
    FB.init({
      appId  : <%= ENV['FACEBOOK_KEY'] %>, // App ID
      status : true, // check login status
      cookie : true, // enable cookies to allow the server to access the session
      xfbml  : true  // parse XFBML
    });
  };

  (function(d) {
    var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
    js = d.createElement('script'); js.id = id; js.async = true;
    js.src = "//connect.facebook.net/en_US/all.js";
    d.getElementsByTagName('head')[0].appendChild(js);
  }(document));

  $(function() {
    $('#connect a.btn.facebook.login').click(function(e) {
      e.preventDefault();

      FB.login(function(response) {
        if (response.authResponse) {
          console.log(response.authResponse)
          $.ajax({
            type: 'POST',
            url: 'http://api.newdayzero.com/provider/auth/facebook/callback',
            dataType: 'json',
            data: {signed_request: response.authResponse.signedRequest, auth_hash: response.authResponse},
            success: function(data, textStatus, jqXHR) {
              // Handle success case
              // window.location = data.redirect_path
            },
            error: function(jqXHR, textStatus, errorThrown) {
              if ($('#connect .error').length <= 0) {
                $('#connect').prepend('<p class="error">An error occurred while attempting to connect with your Facebook account.</p>');
              }
            }
          });
        }
        else{
          if (typeof response.status != "undefined" && response.status != "unknown") {
            if ($('#connect .error').length <= 0) {
              $('#connect').prepend('<p class="error">An error occurred while attempting to connect with your Facebook account.</p>');
            }
          }
        }
      }, {scope: "<%= ENV['FACEBOOK_SCOPE']%>"});
    });
  });
</script>

app/views/home/index.html.haml
%h1 new_day0
- if user_signed_in?
  = "Signed in as #{current_user.email}. Not you?"
  = link_to "Sign out", "http://api.newdayzero.com"+destroy_user_session_path,:method => :delete
- else
  = link_to "Sign up", new_user_registration_path
  or
  = link_to "Sign in", new_user_session_path
  = link_to "Sign in with Facebook", "http://api.newdayzero.com"+auth_provider_user_path(:facebook)

%h2 Ajax Links  
- if user_signed_in?
  = "Signed in as #{current_user.email}. Not you?"
  = link_to "Sign out (not yet ajax)", "http://api.newdayzero.com"+destroy_user_session_path,:method => :delete
- else
  = link_to "Sign up (ajax and json)", ajax_registration_new_path
  <br />
  = link_to "Sign up (just json)", json_registration_new_path
  <br/ >or<br />
  = link_to "Sign in", ajax_session_new_path
  <br />
  = link_to "Sign in with Facebook (not yet ajax)", auth_provider_user_path(:facebook)
  = render partial: "facebook_login"

%div{:"ng-controller" => "HomeCtrl" }
  %h2 Authed Request
  = link_to "Make an authed request", "#", :id => "authed_request", "ng-click" => "getData()"
  <br /><br />
  %h2 Twitter Auth
  =# link_to "Make a twitter auth", "#", "ng-click" => "twitter_sign_in_submit()"
  = link_to "Make a twitter auth", "#", "ng-click" => "open()"
  <br /><br />
  {{data}}
  <br /><br />
  {{status}}

:javascript
  $(document).ready(function(){
  });